# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties
# https://projects.neoforged.net/neoforged/neoforge
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.109

## Mod Properties
mod_id=throwable_slimeball
mod_name=ThrowableSlimeball
mod_license=NRL-1.0
mod_version=1.0.0
mod_group_id=committee.nova
mod_authors=Tapio
mod_description=Allows you to toss slimeballs or magma creams out!
