@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package committee.nova.throwableslimeball.common.item.impl;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;