modLoader = "javafml"
loaderVersion = "[38,)"
license = "Nova Relay License 1.0"
[[mods]]
modId = "throwable_slimeball"
version = "${file.jarVersion}"
displayName = "ThrowableSlimeball"
authors = "Tapio"
description = "Make slimeballs throwable!"
