@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package committee.nova.throwableslimeball;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;