@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package committee.nova.throwableslimeball.common.entity.impl;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;